/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface FrostInterface extends Interface {
    getFunction(nameOrSignature: "measureVerify" | "verify"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'measureVerify', values: [BytesLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'verify', values: [BytesLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'measureVerify', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verify', data: BytesLike): Result;
  }

  

  export interface Frost extends BaseContract {
    
    connect(runner?: ContractRunner | null): Frost;
    waitForDeployment(): Promise<this>;

    interface: FrostInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    measureVerify: TypedContractMethod<
      [message: BytesLike, px: BigNumberish, py: BigNumberish, rx: BigNumberish, ry: BigNumberish, z: BigNumberish, ],
      [[bigint, bigint] & {cold: bigint, warm: bigint }],
      'view'
    >
    

    
    verify: TypedContractMethod<
      [message: BytesLike, px: BigNumberish, py: BigNumberish, rx: BigNumberish, ry: BigNumberish, z: BigNumberish, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'measureVerify'): TypedContractMethod<
      [message: BytesLike, px: BigNumberish, py: BigNumberish, rx: BigNumberish, ry: BigNumberish, z: BigNumberish, ],
      [[bigint, bigint] & {cold: bigint, warm: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'verify'): TypedContractMethod<
      [message: BytesLike, px: BigNumberish, py: BigNumberish, rx: BigNumberish, ry: BigNumberish, z: BigNumberish, ],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }